

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
#   - "alerts/*"
#   - "rules/*"

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
        labels:
          app: '${PROJECT_NAME}_backend'
    metrics_path: /metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          app: '${PROJECT_NAME}_cadvisor'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          app: '${PROJECT_NAME}_prometheus'
